# Site settings
title: Sorting Memo
tag_text: Memo
description: Vision and Progress
url: "http://memo.404notfund.com/"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
